### ISSUE TITLE
Dependency Conflict During SinaTools Installation

### ISSUE THREAD

**Issue by AbdJuma** [SinaLab/sinatools#8]
**Description:**
Encountered a dependency resolution error when installing sinatools using pip. The issue arises due to a strict dependency on torch==1.13.0, causing the installation to fail.

**Steps to Reproduce:**
1- Execute:
bash
pip install sinatools

2- Installation fails with a ResolutionImpossible error.

**Environment:**
OS: Windows 11
Python Version: 3.11.9
pip Version: Latest

**Error Summary:**
The installation attempts multiple sinatools versions but fails due to the strict requirement:
sinatools 0.1.x depends on torch==1.13.0.

Full error logs are attached below :

<img width="941" alt="image" src="https://github.com/user-attachments/assets/0c4d3f24-cb9e-4edc-ac52-3a0b9cb21436">

<img width="945" alt="image" src="https://github.com/user-attachments/assets/bccd6c4f-8b3e-4cca-91ef-49c92e65fcdc">

**Comment by nabila39** [comment]
You can use SinaTools without any issues by creating a virtual environment (VE) and installing Python 3.10.8. After setting up the virtual environment, install SinaTools using pip, and it will work without any errors. This is because SinaTools requires Python version 3.10.8 as mentioned in the documentation.
